from homate.modules.home.domain.device import Device

def default_devices() -> list[Device]:
    """Return initial in-memory device catalog (validated by Pydantic)."""
    raw: list[dict] = [
        {
            "id": "light-living",
            "name": "Đèn phòng khách",
            "room": "living",
            "kind": "bulb",
            "state": {"power": True, "brightness": 60},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "range",
                    "key": "brightness",
                    "label": "Độ sáng",
                    "min": 1,
                    "max": 100,
                    "unit": "%",
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "ac-living",
            "name": "Điều hòa phòng khách",
            "room": "living",
            "kind": "snowflake",
            "state": {
                "power": True,
                "temperature": 26,
                "mode": "cool",
                "fan": "medium",
            },
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "step",
                    "key": "temperature",
                    "label": "Nhiệt độ",
                    "min": 16,
                    "max": 30,
                    "step": 1,
                    "unit": "°C",
                    "when": {"power": True},
                },
                {
                    "type": "enum",
                    "key": "mode",
                    "label": "Chế độ",
                    "options": [
                        {"value": "cool", "label": "Làm lạnh"},
                        {"value": "dry", "label": "Hút ẩm"},
                        {"value": "fan", "label": "Quạt"},
                    ],
                    "when": {"power": True},
                },
                {
                    "type": "enum",
                    "key": "fan",
                    "label": "Tốc độ quạt",
                    "options": [
                        {"value": "low", "label": "Nhẹ"},
                        {"value": "medium", "label": "Vừa"},
                        {"value": "high", "label": "Mạnh"},
                    ],
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "tv-living",
            "name": "TV phòng khách",
            "room": "living",
            "kind": "tv",
            "state": {"power": False},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "speaker-living",
            "name": "Loa phòng khách",
            "room": "living",
            "kind": "speaker",
            "state": {"power": True, "volume": 35},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "range",
                    "key": "volume",
                    "label": "Âm lượng",
                    "min": 0,
                    "max": 100,
                    "unit": "%",
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "heater-living",
            "name": "Máy sưởi phòng khách",
            "room": "living",
            "kind": "flame",
            "state": {"power": False, "temperature": 24},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "step",
                    "key": "temperature",
                    "label": "Nhiệt độ",
                    "min": 16,
                    "max": 30,
                    "step": 1,
                    "unit": "°C",
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "door",
            "name": "Cửa chính",
            "room": "living",
            "kind": "lock",
            "state": {"locked": True},
            "controls": [
                {
                    "type": "action",
                    "key": "unlock",
                    "label": "Mở khóa cửa",
                    "variant": "danger",
                    "sensitive": True,
                },
                {
                    "type": "action",
                    "key": "lock",
                    "label": "Đóng khóa cửa",
                },
            ],
        },
        {
            "id": "cam-entrance",
            "name": "Camera cửa",
            "room": "living",
            "kind": "camera",
            "state": {"recording": True},
            "controls": [
                {"type": "toggle", "key": "recording", "label": "Ghi hình"},
            ],
        },
        {
            "id": "light-bed",
            "name": "Đèn phòng ngủ",
            "room": "bed",
            "kind": "bulb",
            "state": {"power": False},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "ac-bed",
            "name": "Điều hòa phòng ngủ",
            "room": "bed",
            "kind": "snowflake",
            "state": {
                "power": True,
                "temperature": 24,
                "mode": "cool",
                "fan": "low",
            },
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "step",
                    "key": "temperature",
                    "label": "Nhiệt độ",
                    "min": 16,
                    "max": 30,
                    "step": 1,
                    "unit": "°C",
                    "when": {"power": True},
                },
                {
                    "type": "enum",
                    "key": "mode",
                    "label": "Chế độ",
                    "options": [
                        {"value": "cool", "label": "Làm lạnh"},
                        {"value": "dry", "label": "Hút ẩm"},
                        {"value": "fan", "label": "Quạt"},
                    ],
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "curtain",
            "name": "Rèm phòng ngủ",
            "room": "bed",
            "kind": "curtain",
            "state": {"preset": "ajar", "position": 40},
            "controls": [
                {
                    "type": "enum",
                    "key": "preset",
                    "label": "Mức mở",
                    "options": [
                        {"value": "closed", "label": "Đóng"},
                        {"value": "ajar", "label": "Mở hé"},
                        {"value": "open", "label": "Mở hết"},
                    ],
                },
                {
                    "type": "range",
                    "key": "position",
                    "label": "Vị trí",
                    "min": 0,
                    "max": 100,
                    "unit": "%",
                },
            ],
        },
        {
            "id": "fan-bed",
            "name": "Quạt trần phòng ngủ",
            "room": "bed",
            "kind": "fan",
            "state": {"speed": 0},
            "controls": [
                {
                    "type": "level",
                    "key": "speed",
                    "label": "Nút quạt",
                    "levels": [0, 1, 2, 3],
                    "labels": ["Tắt", "1", "2", "3"],
                },
            ],
        },
        {
            "id": "light-kitchen",
            "name": "Đèn bếp",
            "room": "kitchen",
            "kind": "bulb",
            "state": {"power": True},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "plug-kitchen",
            "name": "Ổ nồi cơm",
            "room": "kitchen",
            "kind": "plug",
            "state": {"power": True},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "fan-kitchen",
            "name": "Quạt hút bếp",
            "room": "kitchen",
            "kind": "fan",
            "state": {"speed": 2},
            "controls": [
                {
                    "type": "level",
                    "key": "speed",
                    "label": "Nút quạt",
                    "levels": [0, 1, 2, 3],
                    "labels": ["Tắt", "1", "2", "3"],
                },
            ],
        },
        {
            "id": "light-bath",
            "name": "Đèn phòng tắm",
            "room": "bath",
            "kind": "bulb",
            "state": {"power": False},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "heater-bath",
            "name": "Máy nước nóng",
            "room": "bath",
            "kind": "droplet",
            "state": {"power": True, "temperature": 42},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "step",
                    "key": "temperature",
                    "label": "Nhiệt độ nước",
                    "min": 35,
                    "max": 55,
                    "step": 1,
                    "unit": "°C",
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "fan-bath",
            "name": "Quạt thông gió",
            "room": "bath",
            "kind": "fan",
            "state": {"speed": 0},
            "controls": [
                {
                    "type": "level",
                    "key": "speed",
                    "label": "Nút quạt",
                    "levels": [0, 1, 2],
                    "labels": ["Tắt", "1", "2"],
                },
            ],
        },
        {
            "id": "light-office",
            "name": "Đèn bàn làm việc",
            "room": "office",
            "kind": "bulb",
            "state": {"power": True, "brightness": 80},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "range",
                    "key": "brightness",
                    "label": "Độ sáng",
                    "min": 1,
                    "max": 100,
                    "unit": "%",
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "ac-office",
            "name": "Điều hòa phòng làm việc",
            "room": "office",
            "kind": "snowflake",
            "state": {"power": False, "temperature": 25, "mode": "cool"},
            "controls": [
                {"type": "toggle", "key": "power", "label": "Nguồn"},
                {
                    "type": "step",
                    "key": "temperature",
                    "label": "Nhiệt độ",
                    "min": 16,
                    "max": 30,
                    "step": 1,
                    "unit": "°C",
                    "when": {"power": True},
                },
                {
                    "type": "enum",
                    "key": "mode",
                    "label": "Chế độ",
                    "options": [
                        {"value": "cool", "label": "Làm lạnh"},
                        {"value": "dry", "label": "Hút ẩm"},
                        {"value": "fan", "label": "Quạt"},
                    ],
                    "when": {"power": True},
                },
            ],
        },
        {
            "id": "plug-office",
            "name": "Ổ máy tính",
            "room": "office",
            "kind": "plug",
            "state": {"power": True},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "light-balcony",
            "name": "Đèn ban công",
            "room": "balcony",
            "kind": "bulb",
            "state": {"power": False},
            "controls": [{"type": "toggle", "key": "power", "label": "Nguồn"}],
        },
        {
            "id": "cam-balcony",
            "name": "Camera ban công",
            "room": "balcony",
            "kind": "camera",
            "state": {"recording": True},
            "controls": [
                {"type": "toggle", "key": "recording", "label": "Ghi hình"},
            ],
        },
    ]
    return [Device.model_validate(item) for item in raw]

def mvp_devices() -> list[Device]:
    """Core devices for Sprint 1 demos."""
    return [d for d in default_devices() if d.id in MVP_DEVICE_IDS]
